# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Viet on Rails'
tagline:             'Ruby và nhiều thứ thú vị khác'
description:         ''
url:                 http://vietonrails.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Luu Tuan Anh
  email:             rock.khuya@gmail.com

# Custom vars
version:             1.0.0

gems:                [jekyll-paginate]